package net.thumbtack.school.concert;

import com.google.gson.Gson;
import net.thumbtack.school.concert.dto.request.*;
import net.thumbtack.school.concert.base.UserException;
import net.thumbtack.school.concert.database.DataBase;
import net.thumbtack.school.concert.dto.responce.ConcertDtoResponce;
import net.thumbtack.school.concert.dto.responce.RegisterUserDtoResponce;
import net.thumbtack.school.concert.model.ConcertSong;
import net.thumbtack.school.concert.model.User;
import net.thumbtack.school.concert.server.Server;
import org.junit.Test;
import java.io.IOException;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class TestConcert extends TestBase{

    @Test
    public void testConcert () throws UserException, IOException {
        Server server = new Server();
        server.setServerIsActive();
        Gson gson = new Gson();
        String requestJsonString1 = gson.toJson(new User("Дмитрий", "Ермоленко", "DimaErmol", "likeacat"));
        RegisterUserDtoResponce rudResponce1 = gson.fromJson((server.registerUser(requestJsonString1)), RegisterUserDtoResponce.class);
        AddSongDtoRequest asd1 = new AddSongDtoRequest(rudResponce1.getToken(), "Песня про Жирафа", "Высоцкий", "Высоцкий", "Высоцкий", 137);
        AddSongDtoRequest asd2 = new AddSongDtoRequest(rudResponce1.getToken(), "Вершина", "Высоцкий", "Высоцкий", "Высоцкий", 158);
        AddSongDtoRequest asd3 = new AddSongDtoRequest(rudResponce1.getToken(), "Ну вот исчезла дрожь в руках...", "Высоцкий", "Высоцкий", "Высоцкий", 170);
        AddSongDtoRequest asd4 = new AddSongDtoRequest(rudResponce1.getToken(), "Баллада о любви", "Высоцкий", "Высоцкий", "Высоцкий", 305);
        AddSongDtoRequest asd5 = new AddSongDtoRequest(rudResponce1.getToken(), "Утренняя нимнастика", "Высоцкий", "Высоцкий", "Высоцкий", 182);
        AddSongDtoRequest asd6 = new AddSongDtoRequest(rudResponce1.getToken(), "Баллада о борьбе", "Высоцкий", "Высоцкий", "Высоцкий", 241);
        AddSongDtoRequest asd7 = new AddSongDtoRequest(rudResponce1.getToken(), "Алюминевые огурцы", "Цой", "Цой, Рыбин", "Цой, Рыбин,", 155);
        server.addSong(gson.toJson(asd1));
        server.addSong(gson.toJson(asd2));
        server.addSong(gson.toJson(asd3));
        server.addSong(gson.toJson(asd4));
        server.addSong(gson.toJson(asd5));
        server.addSong(gson.toJson(asd6));
        server.addSong(gson.toJson(asd7));

        String requestJsonString2 = gson.toJson( new User("Кирилл", "Страдов", "KirStrad", "tuztuz@2"));
        RegisterUserDtoResponce rudResponce2 = gson.fromJson((server.registerUser(requestJsonString2)), RegisterUserDtoResponce.class);
        AddSongDtoRequest asd8 = new AddSongDtoRequest(rudResponce2.getToken(),"Восьмиклассница", "Цой", "Цой, Рыбин", "Цой, Рыбин", 162);
        AddSongDtoRequest asd9 = new AddSongDtoRequest(rudResponce2.getToken(),"Видели ночь", "Цой", "Цой, Науменко", "Цой, Науменко", 131);
        AddSongDtoRequest asd10 = new AddSongDtoRequest(rudResponce2.getToken(),"Звезда", "Цой", "Цой", "Цой,", 270);
        AddSongDtoRequest asd11 = new AddSongDtoRequest(rudResponce2.getToken(),"Когда твоя девушка больна", "Цой", "Цой", "Цой,", 260);
        server.addSong(gson.toJson(asd8));
        server.addSong(gson.toJson(asd9));
        server.addSong(gson.toJson(asd10));
        server.addSong(gson.toJson(asd11));

        String requestJsonString3 = gson.toJson( new User("Наташа", "Бровкина", "NatBrov", "pampam%4"));
        RegisterUserDtoResponce rudResponce3 = gson.fromJson((server.registerUser(requestJsonString3)), RegisterUserDtoResponce.class);
        AddSongDtoRequest asd12 = new AddSongDtoRequest(rudResponce3.getToken(),"Я уеду жить в Лондон", "Лепс", "Лепс, Тимати", "Лепс, Тимати", 264);
        AddSongDtoRequest asd13 = new AddSongDtoRequest(rudResponce3.getToken(),"Самый лучший день", "Лепс", "Шапиро", "Шапиро", 302);
        AddSongDtoRequest asd14 = new AddSongDtoRequest(rudResponce3.getToken(),"Я счастливый", "Лепс", "Дубинский", "Паренко", 222);
        AddSongDtoRequest asd15 = new AddSongDtoRequest(rudResponce3.getToken(),"Ты знаешь – так хочется жить", "Лепс", "Лепс", "Лепс", 242);
        server.addSong(gson.toJson(asd12));
        server.addSong(gson.toJson(asd13));
        server.addSong(gson.toJson(asd14));
        server.addSong(gson.toJson(asd15));

        String requestJsonString4 = gson.toJson( new User("Светлана", "Александрова", "SvetaA", "1234567890"));
        RegisterUserDtoResponce rudResponce4 = gson.fromJson((server.registerUser(requestJsonString4)), RegisterUserDtoResponce.class);
        AddSongDtoRequest asd16 = new AddSongDtoRequest(rudResponce4.getToken(),"В серебре", "Animal Джаz", "Animal Джаz", "Animal Джаz", 254);
        AddSongDtoRequest asd17 = new AddSongDtoRequest(rudResponce4.getToken(),"Три полоски", "Animal Джаz", "Animal Джаz", "Animal Джаz,", 250);
        AddSongDtoRequest asd18 = new AddSongDtoRequest(rudResponce4.getToken(),"Шаг вдох", "Animal Джаz", "Animal Джаz", "Animal Джаz", 252);
        AddSongDtoRequest asd19 = new AddSongDtoRequest(rudResponce4.getToken(),"Дальше", "Animal Джаz", "Animal Джаz", "Animal Джаz", 358);
        AddSongDtoRequest asd20 = new AddSongDtoRequest(rudResponce4.getToken(),"Любовь", "Animal Джаz", "Animal Джаz", "Animal Джаz", 223);
        server.addSong(gson.toJson(asd16));
        server.addSong(gson.toJson(asd17));
        server.addSong(gson.toJson(asd18));
        server.addSong(gson.toJson(asd19));
        server.addSong(gson.toJson(asd20));

        String requestJsonString5 = gson.toJson( new User("Любовь", "Наумова", "LubaYm", "123456789"));
        RegisterUserDtoResponce rudResponce5 = gson.fromJson((server.registerUser(requestJsonString5)), RegisterUserDtoResponce.class);
        AddSongDtoRequest asd21 = new AddSongDtoRequest(rudResponce5.getToken(),"Как летать", "МакSим", "Максимова", "Максимова", 196);
        AddSongDtoRequest asd22 = new AddSongDtoRequest(rudResponce5.getToken(),"Бегущая по волнам", "МакSим", "Максимова", "Максимова", 183);
        AddSongDtoRequest asd23 = new AddSongDtoRequest(rudResponce5.getToken(),"Нежность", "МакSим", "Максимова", "Максимова", 275);
        AddSongDtoRequest asd24 = new AddSongDtoRequest(rudResponce5.getToken(),"Вечер", "Пикник", "Шклярский", "Шклярский", 305);
        AddSongDtoRequest asd25 = new AddSongDtoRequest(rudResponce5.getToken(),"Азбука Морзе", "Пикник", "Шклярский", "Шклярский", 257);
        server.addSong(gson.toJson(asd21));
        server.addSong(gson.toJson(asd22));
        server.addSong(gson.toJson(asd23));
        server.addSong(gson.toJson(asd24));
        server.addSong(gson.toJson(asd25));

        // оценки пользователя 1
        AddRatingDtoRequest rdr1_8 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(7),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_8));
        AddRatingDtoRequest rdr1_9 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(8),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_9));
        AddRatingDtoRequest rdr1_10 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(9),rudResponce1.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr1_10));
        AddRatingDtoRequest rdr1_11 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(10),rudResponce1.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr1_11));
        AddRatingDtoRequest rdr1_12 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(11),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_12));
        AddRatingDtoRequest rdr1_13 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(12),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_13));
        AddRatingDtoRequest rdr1_14 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(13),rudResponce1.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr1_14));
        AddRatingDtoRequest rdr1_15 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(14),rudResponce1.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr1_15));
        AddRatingDtoRequest rdr1_16 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(15),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_16));
        AddRatingDtoRequest rdr1_17 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(16),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_17));
        AddRatingDtoRequest rdr1_18 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(17),rudResponce1.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr1_18));
        AddRatingDtoRequest rdr1_19 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(18),rudResponce1.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr1_19));
        AddRatingDtoRequest rdr1_20 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(19),rudResponce1.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr1_20));
        AddRatingDtoRequest rdr1_21 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(20),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_21));
        AddRatingDtoRequest rdr1_22 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(21),rudResponce1.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr1_22));
        AddRatingDtoRequest rdr1_23 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(22),rudResponce1.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr1_23));
        AddRatingDtoRequest rdr1_24 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(23),rudResponce1.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr1_24));
        AddRatingDtoRequest rdr1_25 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(24),rudResponce1.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr1_25));

        // оценки пользователя 2
        AddRatingDtoRequest rdr2_1 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(0),rudResponce2.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr2_1));
        AddRatingDtoRequest rdr2_2 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(1),rudResponce2.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr2_2));
        AddRatingDtoRequest rdr2_3 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(2),rudResponce2.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr2_3));
        AddRatingDtoRequest rdr2_4 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(3),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_4));
        AddRatingDtoRequest rdr2_5 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(4),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_5));
        AddRatingDtoRequest rdr2_6 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(5),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_6));
        AddRatingDtoRequest rdr2_7 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(6),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_7));
        AddRatingDtoRequest rdr2_12 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(11),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_12));
        AddRatingDtoRequest rdr2_13 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(12),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_13));
        AddRatingDtoRequest rdr2_14 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(13),rudResponce2.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr2_14));
        AddRatingDtoRequest rdr2_15 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(14),rudResponce2.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr2_15));
        AddRatingDtoRequest rdr2_16 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(15),rudResponce2.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr2_16));
        AddRatingDtoRequest rdr2_17 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(16),rudResponce2.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr2_17));
        AddRatingDtoRequest rdr2_18 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(17),rudResponce2.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr2_18));
        AddRatingDtoRequest rdr2_19 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(18),rudResponce2.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr2_19));
        AddRatingDtoRequest rdr2_20 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(19),rudResponce2.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr2_20));
        AddRatingDtoRequest rdr2_21 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(20),rudResponce2.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr2_21));
        AddRatingDtoRequest rdr2_22 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(21),rudResponce2.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr2_22));
        AddRatingDtoRequest rdr2_23 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(22),rudResponce2.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr2_23));
        AddRatingDtoRequest rdr2_24 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(23),rudResponce2.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr2_24));
        AddRatingDtoRequest rdr2_25 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(24),rudResponce2.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr2_25));

        // оценки пользователя 3
        AddRatingDtoRequest rdr3_1 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(0),rudResponce3.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr3_1));
        AddRatingDtoRequest rdr3_2 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(1),rudResponce3.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr3_2));
        AddRatingDtoRequest rdr3_3 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(2),rudResponce3.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr3_3));
        AddRatingDtoRequest rdr3_4 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(3),rudResponce3.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr3_4));
        AddRatingDtoRequest rdr3_5 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(4),rudResponce3.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr3_5));
        AddRatingDtoRequest rdr3_6 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(5),rudResponce3.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr3_6));
        AddRatingDtoRequest rdr3_7 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(6),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_7));
        AddRatingDtoRequest rdr3_8 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(7),rudResponce3.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr3_8));
        AddRatingDtoRequest rdr3_9 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(8),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_9));
        AddRatingDtoRequest rdr3_10 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(9),rudResponce3.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr3_10));
        AddRatingDtoRequest rdr3_11 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(10),rudResponce3.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr3_11));
        AddRatingDtoRequest rdr3_16 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(15),rudResponce3.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr3_16));
        AddRatingDtoRequest rdr3_17 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(16),rudResponce3.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr3_17));
        AddRatingDtoRequest rdr3_18 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(17),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_18));
        AddRatingDtoRequest rdr3_19 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(18),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_19));
        AddRatingDtoRequest rdr3_20 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(19),rudResponce3.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr3_20));
        AddRatingDtoRequest rdr3_21 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(20),rudResponce3.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr3_21));
        AddRatingDtoRequest rdr3_22 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(21),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_22));
        AddRatingDtoRequest rdr3_23 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(22),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_23));
        AddRatingDtoRequest rdr3_24 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(23),rudResponce3.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr3_24));
        AddRatingDtoRequest rdr3_25 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(24),rudResponce3.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr3_25));

        // оценки пользователя 4
        AddRatingDtoRequest rdr4_1 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(0),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_1));
        AddRatingDtoRequest rdr4_2 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(1),rudResponce4.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr4_2));
        AddRatingDtoRequest rdr4_3 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(2),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_3));
        AddRatingDtoRequest rdr4_4 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(3),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_4));
        AddRatingDtoRequest rdr4_5 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(4),rudResponce4.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr4_5));
        AddRatingDtoRequest rdr4_6 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(5),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_6));
        AddRatingDtoRequest rdr4_7 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(6),rudResponce4.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr4_7));
        AddRatingDtoRequest rdr4_8 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(7),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_8));
        AddRatingDtoRequest rdr4_9 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(8),rudResponce4.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr4_9));
        AddRatingDtoRequest rdr4_10 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(9),rudResponce4.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr4_10));
        AddRatingDtoRequest rdr4_11 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(10),rudResponce4.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr4_11));
        AddRatingDtoRequest rdr4_12 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(11),rudResponce4.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr4_12));
        AddRatingDtoRequest rdr4_13 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(12),rudResponce4.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr4_13));
        AddRatingDtoRequest rdr4_14 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(13),rudResponce4.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr4_14));
        AddRatingDtoRequest rdr4_15 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(14),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_15));
        AddRatingDtoRequest rdr4_21 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(20),rudResponce4.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr4_21));
        AddRatingDtoRequest rdr4_22 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(21),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_22));
        AddRatingDtoRequest rdr4_23 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(22),rudResponce4.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr4_23));
        AddRatingDtoRequest rdr4_24 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(23),rudResponce4.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr4_24));
        AddRatingDtoRequest rdr4_25 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(24),rudResponce4.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr4_25));

        // оценки пользователя 5
        AddRatingDtoRequest rdr5_1 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(0),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_1));
        AddRatingDtoRequest rdr5_2 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(1),rudResponce5.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr5_2));
        AddRatingDtoRequest rdr5_3 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(2),rudResponce5.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr5_3));
        AddRatingDtoRequest rdr5_4 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(3),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_4));
        AddRatingDtoRequest rdr5_5 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(4),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_5));
        AddRatingDtoRequest rdr5_6 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(5),rudResponce5.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr5_6));
        AddRatingDtoRequest rdr5_7 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(6),rudResponce5.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr5_7));
        AddRatingDtoRequest rdr5_8 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(7),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_8));
        AddRatingDtoRequest rdr5_9 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(8),rudResponce5.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr5_9));
        AddRatingDtoRequest rdr5_10 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(9),rudResponce5.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr5_10));
        AddRatingDtoRequest rdr5_11 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(10),rudResponce5.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr5_11));
        AddRatingDtoRequest rdr5_12 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(11),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_12));
        AddRatingDtoRequest rdr5_13 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(12),rudResponce5.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr5_13));
        AddRatingDtoRequest rdr5_14 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(13),rudResponce5.getToken(), 5);
        server.addOrChangeRating(gson.toJson(rdr5_14));
        AddRatingDtoRequest rdr5_15 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(14),rudResponce5.getToken(), 4);
        server.addOrChangeRating(gson.toJson(rdr5_15));
        AddRatingDtoRequest rdr5_16 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(15),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_16));
        AddRatingDtoRequest rdr5_17 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(16),rudResponce5.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr5_17));
        AddRatingDtoRequest rdr5_18 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(17),rudResponce5.getToken(), 1);
        server.addOrChangeRating(gson.toJson(rdr5_18));
        AddRatingDtoRequest rdr5_19 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(18),rudResponce5.getToken(), 2);
        server.addOrChangeRating(gson.toJson(rdr5_19));
        AddRatingDtoRequest rdr5_20 = new AddRatingDtoRequest(DataBase.getInstance().getSongsList().get(19),rudResponce5.getToken(), 3);
        server.addOrChangeRating(gson.toJson(rdr5_20));

        // комментарии
//        System.out.println(DataBase.getInstance().getSongsList().get(23).getSongName());
        AddSongCommentDtoRequest ascd1 = new AddSongCommentDtoRequest(rudResponce1.getToken(), DataBase.getInstance().getSongsList().get(23), "Нравится очень"); //войдет в assert
        AddSongCommentDtoRequest ascd2 = new AddSongCommentDtoRequest(rudResponce2.getToken(), DataBase.getInstance().getSongsList().get(23), "Хрень");//войдет в assert
        AddSongCommentDtoRequest ascd3 = new AddSongCommentDtoRequest(rudResponce2.getToken(), DataBase.getInstance().getSongsList().get(24), "Старье");
        AddSongCommentDtoRequest ascd4 = new AddSongCommentDtoRequest(rudResponce2.getToken(), DataBase.getInstance().getSongsList().get(22), "Жесть");
        server.addSongComment(gson.toJson(ascd1));
        server.addSongComment(gson.toJson(ascd2));
        server.addSongComment(gson.toJson(ascd3));
        server.addSongComment(gson.toJson(ascd4));
        AddCommentToCommentDtoRequest accd1 = new AddCommentToCommentDtoRequest(rudResponce3.getToken(), DataBase.getInstance().getSongCommentList().get(0) ,"И мне");//войдет в assert
        AddCommentToCommentDtoRequest accd2 = new AddCommentToCommentDtoRequest(rudResponce4.getToken(), DataBase.getInstance().getSongCommentList().get(1) ,"Нормальная песня");//войдет в assert
        AddCommentToCommentDtoRequest accd3 = new AddCommentToCommentDtoRequest(rudResponce3.getToken(), DataBase.getInstance().getSongCommentList().get(2) ,"Хорошая песня из хорошего кино");
        server.addCommentToComment(gson.toJson(accd1));
        server.addCommentToComment(gson.toJson(accd2));
        server.addCommentToComment(gson.toJson(accd3));

        List<ConcertSong> concert = gson.fromJson(server.getConcert(gson.toJson(new ConcertDtoRequest(rudResponce1.getToken()))), ConcertDtoResponce.class).getConcert();
        assertEquals(15,concert.size());
        assertEquals("Восьмиклассница",concert.get(0).getSongName());
        assertEquals("Самый лучший день",concert.get(1).getSongName());
        assertEquals("Вершина",concert.get(2).getSongName());
        assertEquals("Баллада о борьбе",concert.get(3).getSongName());
        assertEquals("Я уеду жить в Лондон",concert.get(4).getSongName());
        assertEquals("Ты знаешь – так хочется жить",concert.get(5).getSongName());
        assertEquals("Песня про Жирафа",concert.get(6).getSongName());
        assertEquals("Ну вот исчезла дрожь в руках...",concert.get(7).getSongName());
        assertEquals("Баллада о любви",concert.get(8).getSongName());
        assertEquals("Когда твоя девушка больна",concert.get(9).getSongName());
        assertEquals("Любовь",concert.get(10).getSongName());
        assertEquals("Вечер",concert.get(11).getSongName());
        assertEquals("Утренняя нимнастика",concert.get(12).getSongName());
        assertEquals("Я счастливый",concert.get(13).getSongName());
        assertEquals("В серебре",concert.get(14).getSongName());

        assertEquals("Вечер", concert.get(11).getSongName());
        assertEquals("Шклярский", concert.get(11).getComposer());
        assertEquals("Шклярский", concert.get(11).getAuthorOfTheText());
        assertEquals("Пикник", concert.get(11).getSinger());
        assertEquals(19, concert.get(11).getSumRating());
        assertEquals("Любовь", concert.get(11).getUserFirstName());
        assertEquals("Наумова", concert.get(11).getUserLastName());

        assertEquals(2, concert.get(11).getConsertSongComment().size());
        assertEquals("Нравится очень", concert.get(11).getConsertSongComment().get(0).getTextOfSongComment());
        assertEquals("Хрень", concert.get(11).getConsertSongComment().get(1).getTextOfSongComment());
        assertEquals(1, concert.get(11).getConsertSongComment().get(0).getConsertCommentsToComments().size());
        assertEquals(1, concert.get(11).getConsertSongComment().get(1).getConsertCommentsToComments().size());
        assertEquals("И мне", concert.get(11).getConsertSongComment().get(0).getConsertCommentsToComments().get(0).getTextOfCommentToComment());
        assertEquals("Нормальная песня", concert.get(11).getConsertSongComment().get(1).getConsertCommentsToComments().get(0).getTextOfCommentToComment());
    }
}
